# Generated by Django 5.1.1 on 2024-09-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
