# Generated by Django 5.1.1 on 2024-09-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_alter_book_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
