# Generated by Django 5.1.1 on 2024-09-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0005_remove_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
